"""empty message

Revision ID: d26ebf5e2060
Revises: bcd7bd9682de
Create Date: 2026-06-24 07:41:13.936930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26ebf5e2060'
down_revision: Union[str, Sequence[str], None] = 'bcd7bd9682de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('no_case', sa.Integer(), nullable=False),
    sa.Column('bad_case', sa.Integer(), nullable=False),
    sa.Column('no_person', sa.Integer(), nullable=False),
    sa.Column('error', sa.Integer(), nullable=False),
    sa.Column('total_seconds', sa.Float(), nullable=False),
    sa.Column('ocr_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_stats')
    # ### end Alembic commands ###
